### ISSUE TITLE
importDocument API does not work in NodeJS

### ISSUE THREAD

**Issue by terrencejames-lf** [Laserfiche/lf-repository-api-client-js#53]
When trying to use the importDocument API in NodeJS, you get
`ReferenceError: FormData is not defined`

Currently, a workaround has not been found. 

Things tried:

- Upgrading to Node16 which includes FormData API
- Installing external NPM module such as form-data
- Using URLSearchParams() instead of FormData

**Comment by jason-chan-lf** [comment]
After this issue is resolved, this test for `entriesClient.getDocumentContentType` should be updated
https://github.com/Laserfiche/lf-repository-api-client-js/pull/57/files#diff-8faed4392abed6f561cf83aa3c8cf6845eb636b634e65d92c91c2496152212a0
