### ISSUE TITLE
Unexpected status codes cause ApiException to be thrown instead of ProblemDetails

### ISSUE THREAD

**Issue by jason-chan-lf** [Laserfiche/lf-repository-api-client-js#63]
Almost all the APIs throw a ProblemDetails exception when a documented non 200 status code is returned. When an undocumented status code is returned, an ApiException is thrown instead. To support consistent error handling, the client library should only throw ProblemDetails when handling API responses.

**Comment by terrencejames-lf** [comment]
Resolved by #68
